{% set name = "orc" %}
{% set version = "0.4.36" %}
{% set sha256 = "83b074cb67317d58bef1e8d0cc862f7ae8a77a45bbff056a1f987c6488b2f5fd" %}

package:
  # apache orc is already registered as 'orc', so we call this gst-orc
  name: gst-{{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - orcc --help
    - orc-bugreport --help
    - pkg-config --print-errors --modversion orc-0.4  # [unix]

about:
  home: http://gstreamer.freedesktop.org/modules/orc.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/orc
  doc_url: http://gstreamer.freedesktop.org/data/doc/orc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Optimized Inner Loop Runtime Compiler
  description: |
    Orc is a library and set of tools for compiling and executing
    very simple programs that operate on arrays of data.  The "language"
    is a generic assembly language that represents many of the features
    available in SIMD architectures, including saturated addition and
    subtraction, and many arithmetic operations.

    At this point, developers interested in using Orc should look at the
    examples and try out a few Orc programs in an experimental branch
    of their own projects.  And provide feedback on how it works.  There
    will likely be some major changes in ease of use from a developer's
    perspective over the next few releases.

    The 0.4 series of Orc releases will be API and ABI compatible, and
    will be incompatible with the 0.5 series when it comes out.

extra:
  recipe-maintainers:
    - duncanmmacleod
