travis:
  secure:
    BINSTAR_TOKEN: N/oZoXsWW/LT9NrHLDrsM5j2Tia7DCwgMf5Hqhp1YzuFKa0a5s8O13BSDGach4GuRV0GfAGqC7OzRjU2LBUdVbiznum0DyhVBBEgEF4IFRXaYY/OteBI68/IseVC4HoYxM7pLBQcS1yt7X8ZJRpIrHQwM2c/Ejn4VPspX1KKXHrOUm6tH+iqdwP3u0FEB8z9zInnvZXypkMEn91FFlzCkc/uGPz5l0Qjs46CnBR+dXjmKLH+Cx6fpFE702cIi0KAujueDSroRvJ3R05czfvV1CBnzmKqwQQ5ziI8goo6o6sHh+TFxboVNlhYeVMl6NC8Uj+UfrcvN9nVMVG6dGUK9LSnqg6KyFjjjicmuUN+dBhpaLQF/rvnx89EM4JY6TtWv2x7S3/9jiyknkoH4wrJDjaV9Y0Jjjj1SPlF4kZQkn3M2AKgUJyAV1tHA6DXXiJHersLJlL0lItqZ3B00gwUZLakZRkO5VV0xtiJiSbuQo8Jq6Uj7n92KDN/xxhNZdo7Y8U6Sp9Y26rxAkzM3IwpY0UYtxRc2K/qTuD87bw7/tQbAnmfhqo6Ph9KwtoB1N5eGh95AMfx/3drY3jODdMs/GBLvQrzeKFsi2NiEJNjm5mWvyid06CC0y/c6cK/4nmDuStP3ZahSwDJPQ3kB2lfjI2a/4E1rkqwwEQOxFSXIEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
